name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted  # 네 맥북에서 실행할 때는 이걸로!

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Python version
        run: python3 --version

      - name: Run tests
        run: python3 -m unittest app_test.py
